// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file rtps_send_distance_sensor_PubSubTypes.h
 * This header file contains the declaration of the serialization functions.
 *
 * This file was generated by the tool fastcdrgen.
 */


#ifndef _RTPS_SEND_DISTANCE_SENSOR__PUBSUBTYPES_H_
#define _RTPS_SEND_DISTANCE_SENSOR__PUBSUBTYPES_H_

#include <fastrtps/TopicDataType.h>

#include "rtps_send_distance_sensor_.h"

/*!
 * @brief This class represents the TopicDataType of the type rtps_send_distance_sensor_ defined by the user in the IDL file.
 * @ingroup RTPS_SEND_DISTANCE_SENSOR_
 */
class rtps_send_distance_sensor_PubSubType : public eprosima::fastrtps::TopicDataType {
public:
        typedef rtps_send_distance_sensor_ type;

	rtps_send_distance_sensor_PubSubType();
	virtual ~rtps_send_distance_sensor_PubSubType();
	bool serialize(void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload);
	bool deserialize(eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data);
        std::function<uint32_t()> getSerializedSizeProvider(void* data);
	bool getKey(void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle);
	void* createData();
	void deleteData(void * data);
	MD5 m_md5;
	unsigned char* m_keyBuffer;
};

#endif // _RTPS_SEND_DISTANCE_SENSOR__PUBSUBTYPES_H_