// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file camera_trigger_.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "camera_trigger_.h"

#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

camera_trigger_::camera_trigger_()
{
    m_timestamp = 0;
    m_timestamp_utc = 0;
    m_seq = 0;
}

camera_trigger_::~camera_trigger_()
{
}

camera_trigger_::camera_trigger_(const camera_trigger_ &x)
{
    m_timestamp = x.m_timestamp;
    m_timestamp_utc = x.m_timestamp_utc;
    m_seq = x.m_seq;
}

camera_trigger_::camera_trigger_(camera_trigger_ &&x)
{
    m_timestamp = x.m_timestamp;
    m_timestamp_utc = x.m_timestamp_utc;
    m_seq = x.m_seq;
}

camera_trigger_& camera_trigger_::operator=(const camera_trigger_ &x)
{
    m_timestamp = x.m_timestamp;
    m_timestamp_utc = x.m_timestamp_utc;
    m_seq = x.m_seq;
    
    return *this;
}

camera_trigger_& camera_trigger_::operator=(camera_trigger_ &&x)
{
    m_timestamp = x.m_timestamp;
    m_timestamp_utc = x.m_timestamp_utc;
    m_seq = x.m_seq;
    
    return *this;
}

size_t camera_trigger_::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;
            
    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);

    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    return current_alignment - initial_alignment;
}

size_t camera_trigger_::getCdrSerializedSize(const camera_trigger_& data, size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);

    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    return current_alignment - initial_alignment;
}

void camera_trigger_::serialize(eprosima::fastcdr::Cdr &scdr) const
{
    scdr << m_timestamp;
    scdr << m_timestamp_utc;
    scdr << m_seq;
}

void camera_trigger_::deserialize(eprosima::fastcdr::Cdr &dcdr)
{
    dcdr >> m_timestamp;
    dcdr >> m_timestamp_utc;
    dcdr >> m_seq;
}

size_t camera_trigger_::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
	size_t current_align = current_alignment;
            




    return current_align;
}

bool camera_trigger_::isKeyDefined()
{
    return false;
}

void camera_trigger_::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
	(void) scdr;
	 
	 
	 
}