// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file obstacle_distance_.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "obstacle_distance_.h"

#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

obstacle_distance_::obstacle_distance_()
{
    m_timestamp = 0;

    m_min_distance = 0;
    m_max_distance = 0;
    m_sensor_type = 0;
    m_increment = 0;
}

obstacle_distance_::~obstacle_distance_()
{
}

obstacle_distance_::obstacle_distance_(const obstacle_distance_ &x)
{
    m_timestamp = x.m_timestamp;
    m_distances = x.m_distances;
    m_min_distance = x.m_min_distance;
    m_max_distance = x.m_max_distance;
    m_sensor_type = x.m_sensor_type;
    m_increment = x.m_increment;
}

obstacle_distance_::obstacle_distance_(obstacle_distance_ &&x)
{
    m_timestamp = x.m_timestamp;
    m_distances = std::move(x.m_distances);
    m_min_distance = x.m_min_distance;
    m_max_distance = x.m_max_distance;
    m_sensor_type = x.m_sensor_type;
    m_increment = x.m_increment;
}

obstacle_distance_& obstacle_distance_::operator=(const obstacle_distance_ &x)
{
    m_timestamp = x.m_timestamp;
    m_distances = x.m_distances;
    m_min_distance = x.m_min_distance;
    m_max_distance = x.m_max_distance;
    m_sensor_type = x.m_sensor_type;
    m_increment = x.m_increment;
    
    return *this;
}

obstacle_distance_& obstacle_distance_::operator=(obstacle_distance_ &&x)
{
    m_timestamp = x.m_timestamp;
    m_distances = std::move(x.m_distances);
    m_min_distance = x.m_min_distance;
    m_max_distance = x.m_max_distance;
    m_sensor_type = x.m_sensor_type;
    m_increment = x.m_increment;
    
    return *this;
}

size_t obstacle_distance_::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;
            
    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);

    current_alignment += ((72) * 2) + eprosima::fastcdr::Cdr::alignment(current_alignment, 2);

    current_alignment += 2 + eprosima::fastcdr::Cdr::alignment(current_alignment, 2);

    current_alignment += 2 + eprosima::fastcdr::Cdr::alignment(current_alignment, 2);

    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);

    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    return current_alignment - initial_alignment;
}

size_t obstacle_distance_::getCdrSerializedSize(const obstacle_distance_& data, size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);

    current_alignment += ((72) * 2) + eprosima::fastcdr::Cdr::alignment(current_alignment, 2);
    current_alignment += 2 + eprosima::fastcdr::Cdr::alignment(current_alignment, 2);

    current_alignment += 2 + eprosima::fastcdr::Cdr::alignment(current_alignment, 2);

    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);

    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    return current_alignment - initial_alignment;
}

void obstacle_distance_::serialize(eprosima::fastcdr::Cdr &scdr) const
{
    scdr << m_timestamp;
    scdr << m_distances;
    scdr << m_min_distance;
    scdr << m_max_distance;
    scdr << m_sensor_type;
    scdr << m_increment;
}

void obstacle_distance_::deserialize(eprosima::fastcdr::Cdr &dcdr)
{
    dcdr >> m_timestamp;
    dcdr >> m_distances;
    dcdr >> m_min_distance;
    dcdr >> m_max_distance;
    dcdr >> m_sensor_type;
    dcdr >> m_increment;
}

size_t obstacle_distance_::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
	size_t current_align = current_alignment;
            







    return current_align;
}

bool obstacle_distance_::isKeyDefined()
{
    return false;
}

void obstacle_distance_::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
	(void) scdr;
	 
	 
	 
	 
	 
	 
}